language: go

go_import_path: github.com/sandromello/wgadmin

notifications:
  email: false

go:
  - 1.13

services:
  - docker

env:
  - GO111MODULE=on

script:
  - make test

after_success:
  - test -n "$TRAVIS_TAG" && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
- provider: script
  skip_cleanup: true
  script: make publish
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
